### PR TITLE
Add gm_blesmont

### PR DESCRIPTION
**Pull request by StrawWagen**

### CODE REVIEW

**Comment by wrefgtzweve** [comment]
screenshot of spawns / zones would be appreciated

**Comment by StrawWagen** [comment]
just the city

**Comment by wrefgtzweve** [comment]
image
would be cool to have spawnpoints here too as you can walk between those buildings for pvp

**Comment by StrawWagen** [comment]
tried basically that exact setup on city25, didnt work out well, people didn't know where to walk to find other pvpers.

**Review by wrefgtzweve — APPROVED** [review]

**Pull request merged**
