### PR TITLE
Add boreas night

### PR DESCRIPTION
**Pull request by StrawWagen**

### CODE REVIEW

**Review by wrefgtzweve — COMMENTED** [review]
why not use the same as the regular boreas?

**Comment by StrawWagen** [comment]
Putting the spawns behind the checkpoint keeps it interesting, 
But boreas's spawns need a rework anyways

**Comment by wrefgtzweve** [comment]
rework them at the same time while you're at it

**Comment by StrawWagen** [comment]
Maybe in another pr

**Pull request closed without merging**
